version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: merch_store
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://admin:123@db/merch_store
      - SECRET_KEY=test897897837hhjfhjwewef
    depends_on:
      - db

volumes:
  pgdata:
